name: wire
description: Communication and data container layers library aimed to decouple UI from business logic
version: 1.6.0
homepage: https://github.com/WiresWare/wire_dart

environment:
  sdk: ">=3.10.3 <4.0.0"

dev_dependencies:
  test:
  build_runner:
  lints:
