name: wire
description: Communication and data container layers library aimed to decouple UI from business logic
version: 1.6.0
homepage: https://github.com/WiresWare/wire_dart

environment:
  sdk: ^3.10.4

dev_dependencies:
  test: ^1.25.6
  lints: ^6.0.0
dependencies:
  oktoast: ^3.4.0
