name: wire_example_todo
description: A web app that uses only native HTML components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: "^3.10.4"

dependencies:
  web: ^1.1.1
  wire: ^1.6.0
  wire_example_shared:
    path: ../_shared

dependency_overrides:
  wire:
    path: ../..

dev_dependencies:
  build_web_compilers: ^4.0.4
  build_runner: ^2.3.2
  build_test:
  lints: ^6.0.0
